version: '3.8'
services:
  frontend:
    #image: acctax
    #volumes:
    #  - .:/app
    #  - /app/node_modules
    #ports:
    #  - "3000:3000"
    #command: npm start

    image: acctax
    container_name: acctax
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true    
  
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: tr87AC
      MYSQL_DATABASE: accnewco_acctax
      MYSQL_USER: accnewco_root
      MYSQL_PASSWORD: tr87AC
    ports:
      - "3306:3306"
    expose:
      - 3306
    restart: always
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

volumes:
  dbdata: